### ISSUE TITLE
how to install it?

### ISSUE THREAD

**Issue by Coucour** [ridhotamma/Project-Roy#1]
Hi,

This is probably a noob question but how do I install the project? it looks perfect but i don't know what i should do to test it.

Thank you

**Comment by ridhotamma** [comment]
Hi,

I've already written the instructions for project installation and setup. Please check out the project's README file.

I recommend using Docker Compose for simplicity. If you choose not to, ensure that MongoDB is running on port 27017 and Redis is set up for background tasks.

**Comment by Coucour** [comment]
Thank you very much for the response. I don't understand how... but I obviously looked before writing and the readme was not complete, it stopped at "Clone the repository:"
I will be able to test. Well done and thank you.
